import type { BuilderCatalogCategory, BuilderCatalogItem } from '~/types'

const defaultOptions = [
  { label: 'Opção 1', value: 'option_1' },
  { label: 'Opção 2', value: 'option_2' },
]

const defaultMatrixRows = [
  { label: 'Linha 1', value: 'row_1' },
  { label: 'Linha 2', value: 'row_2' },
]

const defaultMatrixColumns = [
  { label: 'Coluna 1', value: 'column_1', type: 'default' },
  { label: 'Coluna 2', value: 'column_2', type: 'default' },
]

function createStructureCells(rowCount: number, columnCount: number) {
  return Array.from({ length: rowCount }, (_, rowIndex) =>
    Array.from({ length: columnCount }, (_, columnIndex) => {
      const row = `row_${rowIndex + 1}`
      const column = `column_${columnIndex + 1}`
      return {
        name: `${row}__${column}`,
        label: `Linha ${rowIndex + 1} / Coluna ${columnIndex + 1}`,
        row,
        column,
        children: [],
      }
    })).flat()
}

export const builderFieldCatalog: BuilderCatalogItem[] = [
  {
    category: 'fields',
    name: 'text',
    icon: 'text_format',
    title: 'Entrada de texto',
    description: 'Texto de uma única linha',
    schema: { $formkit: 'q-input', name: 'text', label: 'Texto', inputType: 'text' },
  },
  {
    category: 'fields',
    name: 'number',
    icon: '123',
    title: 'Entrada numérica',
    description: 'Digite apenas números',
    schema: { $formkit: 'q-input', name: 'number', label: 'Número', inputType: 'number', validation: 'number' },
  },
  {
    category: 'fields',
    name: 'email',
    icon: 'alternate_email',
    title: 'Endereço de email',
    description: 'Entrada de texto que espera um email',
    schema: { $formkit: 'q-input', name: 'email', label: 'Email', inputType: 'email', validation: 'email' },
  },
  {
    category: 'fields',
    name: 'phone',
    icon: 'phone',
    title: 'Número de telefone',
    description: 'Número de telefone com máscara local',
    schema: { '$formkit': 'q-input', 'name': 'phone', 'label': 'Telefone', 'inputType': 'tel', 'mask': '(##) #####-####', 'unmasked-value': true },
  },
  {
    category: 'fields',
    name: 'password',
    icon: 'password',
    title: 'Senha',
    description: 'Entrada de texto que espera uma senha',
    schema: { $formkit: 'q-input', name: 'password', label: 'Senha', inputType: 'password' },
  },
  {
    category: 'fields',
    name: 'url',
    icon: 'link',
    title: 'URL',
    description: 'Entrada de texto que espera uma URL',
    schema: { $formkit: 'q-input', name: 'url', label: 'URL', inputType: 'url', validation: 'url' },
  },
  {
    category: 'fields',
    name: 'textarea',
    icon: 'wrap_text',
    title: 'Área de texto',
    description: 'Única linha ou multilinhas',
    schema: { $formkit: 'q-input', name: 'textarea', label: 'Área de texto', inputType: 'textarea' },
  },
  {
    category: 'fields',
    name: 'editor',
    icon: 'edit_note',
    title: 'Editor WYSIWYG',
    description: 'Editor de texto rico',
    schema: { $formkit: 'q-editor', name: 'editor', label: 'Editor' },
  },
  {
    category: 'fields',
    name: 'signature',
    icon: 'draw',
    title: 'Assinatura',
    description: 'Assinatura em canvas local',
    schema: { $formkit: 'q-signature', name: 'signature', label: 'Assinatura' },
  },
  {
    category: 'fields',
    name: 'checkbox',
    icon: 'check_box',
    title: 'Caixa de seleção',
    description: 'Entrada de simples marcação',
    schema: { $formkit: 'q-checkbox', name: 'checkbox', label: 'Caixa de seleção' },
  },
  {
    category: 'fields',
    name: 'checkbox_group',
    icon: 'checklist',
    title: 'Grupo de checkboxes',
    description: 'Opções de checkbox',
    schema: { $formkit: 'q-option-group', name: 'checkboxGroup', label: 'Opções', groupType: 'checkbox', options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'checkbox_blocks',
    icon: 'grid_view',
    title: 'Checkbox em blocos',
    description: 'Opções de checkbox como blocos',
    schema: { $formkit: 'q-option-group', name: 'checkboxBlocks', label: 'Blocos', groupType: 'checkbox', optionStyle: 'blocks', options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'checkbox_tabs',
    icon: 'tab',
    title: 'Checkbox em abas',
    description: 'Opções de checkbox mascaradas como abas',
    schema: { $formkit: 'q-btn-toggle', name: 'checkboxTabs', label: 'Abas', multiple: true, options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'radio',
    icon: 'radio_button_checked',
    title: 'Radio',
    description: 'Entrada de rádio simples',
    schema: { $formkit: 'q-option-group', name: 'radio', label: 'Radio', groupType: 'radio', options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'radio_group',
    icon: 'radio_button_checked',
    title: 'Grupo de radio',
    description: 'Opções de radio',
    schema: { $formkit: 'q-option-group', name: 'radioGroup', label: 'Opções', groupType: 'radio', options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'radio_blocks',
    icon: 'view_agenda',
    title: 'Radio em blocos',
    description: 'Opções de radio como blocos',
    schema: { $formkit: 'q-option-group', name: 'radioBlocks', label: 'Blocos', groupType: 'radio', optionStyle: 'blocks', options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'radio_tabs',
    icon: 'tab',
    title: 'Radio em abas',
    description: 'Opções de radio mascaradas como abas',
    schema: { $formkit: 'q-btn-toggle', name: 'radioTabs', label: 'Abas', options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'matrix',
    icon: 'apps',
    title: 'Matriz',
    description: 'Matriz de campos de texto',
    schema: { $formkit: 'q-matrix', name: 'matrix', label: 'Matriz', rows: defaultMatrixRows, columnsConfig: defaultMatrixColumns },
  },
  {
    category: 'fields',
    name: 'matrix_table',
    icon: 'table_chart',
    title: 'Tabela matriz',
    description: 'Tabela de entradas de texto',
    schema: { $formkit: 'q-matrix', name: 'matrixTable', label: 'Tabela matriz', inputType: 'matrix-table', table: true, matrixView: 'table', rows: defaultMatrixRows, columnsConfig: defaultMatrixColumns },
  },
  {
    category: 'fields',
    name: 'toggle',
    icon: 'toggle_on',
    title: 'Toggle',
    description: 'Botão liga/desliga',
    schema: { $formkit: 'q-toggle', name: 'toggle', label: 'Toggle' },
  },
  {
    category: 'fields',
    name: 'select',
    icon: 'arrow_drop_down',
    title: 'Selecionar',
    description: 'Uma única escolha',
    schema: { $formkit: 'q-select', name: 'select', label: 'Selecione', inputType: 'select', options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'multiselect',
    icon: 'list',
    title: 'Multi seleção',
    description: 'Seleção de múltiplas opções',
    schema: { $formkit: 'q-select', name: 'multiselect', label: 'Selecione', inputType: 'multiselect', multiple: true, useChips: true, options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'tags',
    icon: 'sell',
    title: 'Tags',
    description: 'Entrada de tags',
    schema: { $formkit: 'q-select', name: 'tags', label: 'Tags', inputType: 'tags', multiple: true, useChips: true, useInput: true, newValueMode: 'add-unique', options: defaultOptions },
  },
  {
    category: 'fields',
    name: 'date',
    icon: 'event',
    title: 'Data',
    description: 'Entrada para seleção de data',
    schema: { $formkit: 'q-date', name: 'date', label: 'Data' },
  },
  {
    category: 'fields',
    name: 'datetime',
    icon: 'event_available',
    title: 'Data e hora',
    description: 'Entrada para data e hora',
    schema: { $formkit: 'q-datetime', name: 'datetime', label: 'Data e hora' },
  },
  {
    category: 'fields',
    name: 'time',
    icon: 'schedule',
    title: 'Hora',
    description: 'Entrada para seleção de hora',
    schema: { $formkit: 'q-time', name: 'time', label: 'Hora' },
  },
  {
    category: 'fields',
    name: 'date_multiple',
    icon: 'event_repeat',
    title: 'Datas múltiplas',
    description: 'Seleção de várias datas',
    schema: { $formkit: 'q-date-multiple', name: 'multipleDates', label: 'Datas' },
  },
  {
    category: 'fields',
    name: 'date_range',
    icon: 'date_range',
    title: 'Intervalo de datas',
    description: 'Seleção de intervalo de datas',
    schema: { $formkit: 'q-date-range', name: 'dateRange', label: 'Intervalo de datas' },
  },
  {
    category: 'fields',
    name: 'slider',
    icon: 'linear_scale',
    title: 'Slider',
    description: 'Slider horizontal',
    schema: { $formkit: 'q-slider', name: 'slider', label: 'Slider', min: 0, max: 100, step: 1 },
  },
  {
    category: 'fields',
    name: 'range_slider',
    icon: 'settings_ethernet',
    title: 'Slider de intervalo',
    description: 'Slider horizontal com intervalo',
    schema: { $formkit: 'q-range', name: 'rangeSlider', label: 'Intervalo', min: 0, max: 100, step: 1 },
  },
  {
    category: 'fields',
    name: 'vertical_slider',
    icon: 'swap_vert',
    title: 'Slider vertical',
    description: 'Slider vertical',
    schema: { $formkit: 'q-slider', name: 'verticalSlider', label: 'Slider vertical', inputType: 'vertical-slider', vertical: true, min: 0, max: 100, step: 1 },
  },
  {
    category: 'fields',
    name: 'file_upload',
    icon: 'insert_drive_file',
    title: 'Enviar arquivo',
    description: 'Entrada para envio de arquivo',
    schema: { $formkit: 'q-file', name: 'file', label: 'Arquivo', inputType: 'file', clearable: true },
  },
  {
    category: 'fields',
    name: 'multifile_upload',
    icon: 'file_copy',
    title: 'Enviar arquivos',
    description: 'Entrada para envio de arquivos',
    schema: { $formkit: 'q-file', name: 'multifile', label: 'Arquivos', inputType: 'file', multiple: true, useChips: true, clearable: true },
  },
  {
    category: 'fields',
    name: 'image_upload',
    icon: 'image',
    title: 'Enviar imagem',
    description: 'Envio de arquivo apenas imagem',
    schema: { $formkit: 'q-file', name: 'image', label: 'Imagem', inputType: 'image', accept: 'image/*', clearable: true },
  },
  {
    category: 'fields',
    name: 'multiimage_upload',
    icon: 'collections',
    title: 'Enviar imagens',
    description: 'Envio de múltiplas imagens',
    schema: { $formkit: 'q-file', name: 'images', label: 'Imagens', inputType: 'image', accept: 'image/*', multiple: true, useChips: true, clearable: true },
  },
  {
    category: 'fields',
    name: 'gallery',
    icon: 'photo_library',
    title: 'Galeria',
    description: 'Upload de imagens com pré-visualização',
    schema: { $formkit: 'q-file', name: 'gallery', label: 'Galeria', inputType: 'gallery', accept: 'image/*', multiple: true, useChips: true, gallery: true, clearable: true },
  },
  {
    category: 'fields',
    name: 'hidden',
    icon: 'visibility_off',
    title: 'Campo oculto',
    description: 'Entrada oculta',
    schema: { $formkit: 'q-input', name: 'hidden', label: 'Oculto', inputType: 'hidden' },
  },
  {
    category: 'statics',
    name: 'submit_button',
    icon: 'check',
    title: 'Botão de submissão',
    description: 'Botão que conclui o formulário',
    schema: { $formkit: 'q-btn', name: 'submit', buttonLabel: 'Finalizar', bind: '$submitAttrs', ignore: true, type: 'submit', disabled: '$disabled' },
  },
  {
    category: 'statics',
    name: 'reset_button',
    icon: 'restart_alt',
    title: 'Botão de reset',
    description: 'Botão que limpa o formulário',
    schema: { $formkit: 'q-btn', name: 'reset', buttonLabel: 'Limpar', ignore: true, type: 'reset', color: 'grey' },
  },
  {
    category: 'statics',
    name: 'primary_button',
    icon: 'star',
    title: 'Botão primário',
    description: 'Botão de cor primária',
    schema: { $formkit: 'q-btn', name: 'primaryButton', buttonLabel: 'Botão', color: 'primary', ignore: true, type: 'button' },
  },
  {
    category: 'statics',
    name: 'secondary_button',
    icon: 'add',
    title: 'Botão secundário',
    description: 'Botão de cor secundária',
    schema: { $formkit: 'q-btn', name: 'secondaryButton', buttonLabel: 'Botão', color: 'secondary', ignore: true, type: 'button' },
  },
  {
    category: 'statics',
    name: 'danger_button',
    icon: 'warning',
    title: 'Botão risco',
    description: 'Botão de cor negativa',
    schema: { $formkit: 'q-btn', name: 'dangerButton', buttonLabel: 'Botão', color: 'negative', ignore: true, type: 'button' },
  },
  {
    category: 'statics',
    name: 'h1',
    icon: 'sym_o_format_h1',
    title: 'Cabeçalho H1',
    description: 'Elemento HTML <h1>',
    schema: { $el: 'h1', name: 'h1', children: 'Lorem ipsum dolor', attrs: { class: 'no-margin' } },
  },
  {
    category: 'statics',
    name: 'h2',
    icon: 'sym_o_format_h2',
    title: 'Cabeçalho H2',
    description: 'Elemento HTML <h2>',
    schema: { $el: 'h2', name: 'h2', children: 'Lorem ipsum dolor', attrs: { class: 'no-margin' } },
  },
  {
    category: 'statics',
    name: 'h3',
    icon: 'sym_o_format_h3',
    title: 'Cabeçalho H3',
    description: 'Elemento HTML <h3>',
    schema: { $el: 'h3', name: 'h3', children: 'Lorem ipsum dolor', attrs: { class: 'no-margin' } },
  },
  {
    category: 'statics',
    name: 'h4',
    icon: 'sym_o_format_h4',
    title: 'Cabeçalho H4',
    description: 'Elemento HTML <h4>',
    schema: { $el: 'h4', name: 'h4', children: 'Lorem ipsum dolor', attrs: { class: 'no-margin' } },
  },
  {
    category: 'statics',
    name: 'paragraph',
    icon: 'sym_o_format_paragraph',
    title: 'Parágrafo',
    description: 'Elemento HTML <p>',
    schema: { $el: 'p', name: 'p', children: 'Lorem ipsum dolor', attrs: { class: 'no-margin' } },
  },
  {
    category: 'statics',
    name: 'blockquote',
    icon: 'format_quote',
    title: 'Citação',
    description: 'Elemento HTML <quote>',
    schema: { $el: 'blockquote', name: 'blockquote', children: 'Lorem ipsum dolor', attrs: { class: 'text-grey' } },
  },
  {
    category: 'statics',
    name: 'image_static',
    icon: 'image',
    title: 'Imagem',
    description: 'Elemento HTML <img>',
    schema: { $el: 'img', name: 'image', attrs: { src: 'https://placehold.co/640x360', alt: 'Imagem', class: 'full-width rounded-borders' } },
  },
  {
    category: 'statics',
    name: 'link_static',
    icon: 'link',
    title: 'Link',
    description: 'Elemento HTML <a>',
    schema: { $el: 'a', name: 'link', children: 'Link', attrs: { href: '#', target: '_blank', rel: 'noopener' } },
  },
  {
    category: 'statics',
    name: 'separator',
    icon: 'horizontal_rule',
    title: 'Separador',
    description: 'Linha horizontal divisória',
    schema: { $formkit: 'q-separator', name: 'separator', color: 'grey-5', spaced: true },
  },
  {
    category: 'statics',
    name: 'static_html',
    icon: 'code',
    title: 'HTML estático',
    description: 'Elemento HTML simples',
    schema: { $el: 'div', name: 'staticHtml', children: 'Conteúdo estático', attrs: { class: 'text-body2' } },
  },
  {
    category: 'structures',
    name: 'tabs',
    icon: 'tab',
    title: 'Abas',
    description: 'Divide formulários em abas',
    schema: { $formkit: 'q-tabs', name: 'tabs', tabs: [{ name: 'tab_1', label: 'Aba 1', children: [] }, { name: 'tab_2', label: 'Aba 2', children: [] }] },
  },
  {
    category: 'structures',
    name: 'stepper',
    icon: 'linear_scale',
    title: 'Passos',
    description: 'Estrutura de múltiplas etapas',
    schema: { $formkit: 'q-stepper', name: 'stepper', steps: [{ name: 'step_1', label: 'Passo 1', children: [] }] },
  },
  {
    category: 'structures',
    name: 'grid',
    icon: 'grid_on',
    title: 'Grid',
    description: 'Cria layouts complexos',
    schema: { $formkit: 'q-grid', name: 'grid', rowsCount: 2, columnsCount: 2, cells: createStructureCells(2, 2) },
  },
  {
    category: 'structures',
    name: 'table_structure',
    icon: 'table_chart',
    title: 'Tabela',
    description: 'Organiza dados em linhas e colunas',
    schema: { $formkit: 'q-table-structure', name: 'table', rows: defaultMatrixRows, columnsConfig: defaultMatrixColumns, cells: createStructureCells(2, 2) },
  },
  {
    category: 'structures',
    name: 'container',
    icon: 'crop_free',
    title: 'Container',
    description: 'Agrupa elementos',
    schema: { $formkit: 'q-container', name: 'container', label: 'Container', children: [] },
  },
  {
    category: 'structures',
    name: 'two_columns',
    icon: 'view_column',
    title: '2 colunas',
    description: 'Duas colunas lado a lado',
    schema: { $formkit: 'q-grid', name: 'twoColumns', rowsCount: 1, columnsCount: 2, cells: createStructureCells(1, 2) },
  },
  {
    category: 'structures',
    name: 'three_columns',
    icon: 'view_column',
    title: '3 colunas',
    description: 'Três colunas lado a lado',
    schema: { $formkit: 'q-grid', name: 'threeColumns', rowsCount: 1, columnsCount: 3, cells: createStructureCells(1, 3) },
  },
  {
    category: 'structures',
    name: 'four_columns',
    icon: 'view_column',
    title: '4 colunas',
    description: 'Quatro colunas lado a lado',
    schema: { $formkit: 'q-grid', name: 'fourColumns', rowsCount: 1, columnsCount: 4, cells: createStructureCells(1, 4) },
  },
  {
    category: 'structures',
    name: 'list',
    icon: 'format_list_bulleted',
    title: 'Lista',
    description: 'Elemento repetível simples',
    schema: { $formkit: 'q-list-structure', name: 'list', label: 'Lista', nested: false, children: [] },
  },
  {
    category: 'structures',
    name: 'nested_list',
    icon: 'playlist_add',
    title: 'Lista aninhada',
    description: 'Elementos repetíveis em objeto',
    schema: { $formkit: 'q-list-structure', name: 'nestedList', label: 'Lista aninhada', nested: true, children: [] },
  },
]

export function getBuilderCatalogByCategory(category: BuilderCatalogCategory): BuilderCatalogItem[] {
  return builderFieldCatalog.filter(item => item.category === category)
}
